server:
  port: 8080
  forward-headers-strategy: framework

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  datasource:
    password: bcb@1234
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5433/taskDB
  jpa:
    hibernate:
      show-sql: true
#      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
security:
  oauth2:
    client:
      clientId: staybook
      clientSecret: password
      accessTokenUri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token
      user-info-uri:  http://localhost:8080/userinfo
    resourceserver:
      jwt:
        issuer-uri: http://localhost:8080/oauth/token       


