server:
  port: 8081
  forward-headers-strategy: framework
 
spring:
  datasource:
    password: bcb@1234
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5433/taskDB
  jpa:
    hibernate:
#      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
springfox:
  documentation:
    swagger-ui:
      enabled: true
    api-docs:
      enabled: true
  swagger:
    v2:
      use-default-response-messages: false
      tags-order: ascending
      
